# Generated by Django 5.1 on 2024-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
