# Generated by Django 5.1 on 2024-08-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tweet_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
